// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminCardBox: typeof import('./src/components/common/AdminCardBox.vue')['default'];
    AppIcon: typeof import('./src/components/common/AppIcon.vue')['default'];
    ArticleInfo: typeof import('./src/components/toc/articleInfo.vue')['default'];
    CardArticleInfo: typeof import('./src/components/toc/CardArticleInfo.vue')['default'];
    CardNotice: typeof import('./src/components/toc/CardNotice.vue')['default'];
    CardTag: typeof import('./src/components/toc/CardTag.vue')['default'];
    CardUserInfo: typeof import('./src/components/toc/CardUserInfo.vue')['default'];
    CommonPage: typeof import('./src/components/common/CommonPage.vue')['default'];
    EditorMarkdown: typeof import('./src/components/common/EditorMarkdown.vue')['default'];
    ElAffix: typeof import('element-plus/es')['ElAffix'];
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElAvatar: typeof import('element-plus/es')['ElAvatar'];
    ElBacktop: typeof import('element-plus/es')['ElBacktop'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup'];
    ElCol: typeof import('element-plus/es')['ElCol'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElFooter: typeof import('element-plus/es')['ElFooter'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElLink: typeof import('element-plus/es')['ElLink'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElPagination: typeof import('element-plus/es')['ElPagination'];
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElSwitch: typeof import('element-plus/es')['ElSwitch'];
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    ElUpload: typeof import('element-plus/es')['ElUpload'];
    FormSelectV2: typeof import('./src/components/tome/FormSelectV2.vue')['default'];
    Loading: typeof import('element-plus/es')['ElLoadingDirective'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    UserInfo: typeof import('./src/components/common/userInfo.vue')['default'];
  }
}

export {};
